name: docker image

on:
  push:
    branches: [ master, gis-based-mode-detection, cleanup-cicd ]

# Dockerhub credentials are set as environment variables
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      date: ${{ steps.date.outputs.date }}

    steps:
    - uses: actions/checkout@v2

    - name: Set docker image tags
      id: set-tags
      run: |
        set -a; source .env.tags; set +a
        echo "SERVER_IMAGE_TAG=${SERVER_IMAGE_TAG}" >> "$GITHUB_OUTPUT"
        echo "Current server image tag (push): ${SERVER_IMAGE_TAG}"

    - name: docker login
      run: | # log into docker hub account
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Get current date # get the date of the build
      id: date
      run: echo "date=$(date +'%Y-%m-%d--%M-%S')" >> "$GITHUB_OUTPUT"

    #Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo running in repo ${GITHUB_REPOSITORY#*/} branch ${GITHUB_REF##*/} on ${{ steps.date.outputs.date }}

    # Runs a set of commands using the runners shell
    - name: build docker image
      run: |
        docker build -t $DOCKER_USER/${GITHUB_REPOSITORY#*/}:${GITHUB_REF##*/}_${{ steps.date.outputs.date }} .
        docker images

    - name: push docker image
      run: |
        docker push $DOCKER_USER/${GITHUB_REPOSITORY#*/}:${GITHUB_REF##*/}_${{ steps.date.outputs.date }}

    - name: Update .env.tags file 
      run: |
        echo "SERVER_IMAGE_TAG=${{ steps.date.outputs.date }}" > .env.tags

    - name: Add, Commit, Push changes to .env.tags file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Github Actions bot to update .env.tags with latest tags"
        if git diff --quiet; then
          echo "Latest timestamp already present in .env.tags file, no changes to commit"
        else
          git add .env.tags
          git commit -m "Updated docker image tags in .env.tags file to the latest timestamp"
          git push origin 
        fi

    - name: Create artifact text file
      run: |
        echo ${{ steps.date.outputs.date }} > tag_file.txt
        echo "Created tag text file"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image-tag
        path: tag_file.txt
        overwrite: true

  dispatch:
    needs: build
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_TAG: ${{ needs.build.outputs.date }}

    strategy:
      matrix:
        include:
          - repo: e-mission/op-admin-dashboard
            branch: master
          - repo: e-mission/em-public-dashboard
            branch: main

    steps:
    - uses: actions/checkout@v4

    - name: Trigger workflow in admin-dash, public-dash
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_FG_PAT_TAGS }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ matrix.repo }}/actions/workflows/image_build_push.yml/dispatches \
          -d '{"ref":"${{ matrix.branch }}", "inputs": {"docker_image_tag" : "${{ env.DOCKER_IMAGE_TAG }}"}}'
