name: docker image

on:
  push:
    branches: [ master, gis-based-mode-detection ]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

#Dockerhub credentials are set as environment variables
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

jobs:
  test-with-docker:
    uses: e-mission/e-mission-server/.github/workflows/test-with-docker.yml@master

  test-with-manual-install:
    uses: e-mission/e-mission-server/.github/workflows/test-with-manual-install.yml@master

  get-branch-name:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.get-branch-name.outputs.branch_name }}
    steps:
      - name: Get branch name based on ref_type
        id: get-branch-name
        run: |
          echo "Ref: ${{ github.ref }}"
          echo "Ref name: ${{ github.ref_name }}"
          echo "Ref type: ${{ github.ref_type }}"
          echo "Github event base ref: ${{ github.event.base_ref }}"
          if [ "${{ github.ref_type }}" == "tag" ]; then
            base_ref=${{ github.event.base_ref }}
            echo "branch_name=${base_ref#refs/heads/}" >> "$GITHUB_OUTPUT"
          elif [ "${{ github.ref_type }}" == "branch" ]; then
            echo "branch_name=${GITHUB_REF##*/}" >> "$GITHUB_OUTPUT"    
          fi

  build:
    if: ${{ !contains(github.event.head_commit.author.name, 'Github Actions bot to update .env with latest tags') && github.ref_type == 'tag' }}
    needs: [test-with-docker, test-with-manual-install, get-branch-name]
    uses: e-mission/e-mission-server/.github/workflows/reusable_image_build_push.yml@master
    with:
      repo: ${{ github.event.repository.name }}
      branch: ${{ needs.get-branch-name.outputs.branch_name }}
    secrets: inherit

  dispatch:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - repo: e-mission/op-admin-dashboard
            branch: master
          - repo: e-mission/em-public-dashboard
            branch: main

    steps:
    - uses: actions/checkout@v4

    - name: Trigger workflow in admin-dash, public-dash
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_FG_PAT_TAGS }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ matrix.repo }}/actions/workflows/image_build_push.yml/dispatches \
          -d '{"ref":"${{ matrix.branch }}"}'
